---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex02-multitier-fe-deploy
  labels:
    app: ex02-multitier-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ex02-multitier-fe
  template:
    metadata:
      labels:
        app: ex02-multitier-fe
    spec:
      containers:
      - name: fe
        image: dash886/network-fe:1.0.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
        ports:
        - containerPort: 3000
