---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex02-multitier-redis-deploy
  labels:
    app: ex02-multitier-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex02-multitier-redis
  template:
    metadata:
      labels:
        app: ex02-multitier-redis
    spec:
      # initContainers:
      # - name: init-config
      #   image: busybox:1.28
      #   command: ["sh", "-c",  "'cp /redis-master-raw/redis.conf /redis-master/redis.conf && echo require-pass\ $REDIS_PASS >>/redis-master/redis.conf'"]
      #   resources:
      #     requests:
      #       cpu: 20m
      #       memory: 50Mi
      containers:
      - name: redis
        image: redis:7.4
        imagePullPolicy: Always
        env:
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: ex02-multitier-redis-creds
                key: password
        livenessProbe:
          exec:
            command:
              - redis-cli
              - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        command:
          - redis-server
        readinessProbe:
          exec:
            command:
              - redis-cli
              - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
        ports:
          - containerPort: 6379

        volumeMounts:
           - mountPath: /redis-master-data
             name: data
           - mountPath: /redis-master-raw
             name: config

      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: ex02-multitier-redis-config-cm
          items:
          - key: redis-config
            path: redis.conf
