---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex02-multitier-be-deploy
  labels:
    app: ex02-multitier-be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ex02-multitier-be
  template:
    metadata:
      labels:
        app: ex02-multitier-be
    spec:
      containers:
      - name: be
        env:
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: ex02-multitier-be-settings-cm
                # Specify the key associated with the value
                key: REDIS_HOST
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: ex02-multitier-be-settings-cm
                # Specify the key associated with the value
                key: REDIS_PORT
        image: dash886/network-be:1.0.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
        ports:
        - containerPort: 5000
